# Generated by Django 2.1.1 on 2021-05-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitesApp', '0020_auto_20180619_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rRemark',
            field=models.IntegerField(default=1, verbose_name='备注(0:已办、1:待办、2:计划、3:归档、4:取消)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uIcon',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads', verbose_name='头像'),
        ),
    ]
